---
title: "Hw4 Week4 - Shivam - Dacss"
output: html_notebook
---

```{r}
#Reset Enviorment
rm(list = ls())
```

```{r}
#load required library 
library(tidyr)
```

```{r}
#load CIA datasets 
linkIMR   <- "https://github.com/DACSS-601-SHIVAM/HW-WEEK3/raw/refs/heads/main/clean_infant_mortality.csv"
linkLEAB  <- "https://github.com/DACSS-601-SHIVAM/HW-WEEK3/raw/refs/heads/main/clean_life_expectancy.csv"
linkMMR   <- "https://github.com/DACSS-601-SHIVAM/HW-WEEK3/raw/refs/heads/main/clean_maternal_mortality.csv"
```

```{r}
#Read Cia datasets
imr_data  <- read.csv(linkIMR)
leab_data <- read.csv(linkLEAB)
mmr_data  <- read.csv(linkMMR)

# Drop the first index column
imr_data  <- imr_data[, -1]
leab_data <- leab_data[, -1]
mmr_data  <- mmr_data[, -1]

# Rename variables
names(imr_data)[names(imr_data) == "variable"]  <- "infant_mortality_rate"
names(leab_data)[names(leab_data) == "variable"] <- "life_expectancy_at_birth"
names(mmr_data)[names(mmr_data) == "variable"]  <- "maternal_mortality_ratio"
```



```{r}
#Exercise #1 - Merging 
# Merge IMR and LEAB
# Merge with MMR
# Inspect merged data
# Save merged file
# Verify file creation

e1_merge <- merge(
  merge(imr_data, leab_data, by = c("country", "region"), all = TRUE),
  mmr_data,
  by = c("country", "region"),
  all = TRUE
)

str(e1_merge)

write.csv(e1_merge, "e1_merged_data.csv", row.names = FALSE)
str(read.csv("e1_merged_data.csv"))
```

```{r}
#Exercise #2 - Aggregating 

# Aggregate by region using mean
e2_aggregate <- aggregate(
  cbind(
    infant_mortality_rate,
    life_expectancy_at_birth,
    maternal_mortality_ratio
  ) ~ region,
  data = e1_merge,
  FUN = mean,
  na.rm = TRUE
)

# Inspect aggregated data
str(e2_aggregate)

# Save aggregated file
write.csv(e2_aggregate, "e2_aggregate_data.csv", row.names = FALSE)

# Verify file creation
str(read.csv("e2_aggregate_data.csv"))

```

```{r}
#Exercise 3 - Reshaping 

e3_reshape <- pivot_longer(
  e1_merge,
  cols = c(
    infant_mortality_rate,
    life_expectancy_at_birth,
    maternal_mortality_ratio
  ),
  names_to = "indicator",
  values_to = "value"
)

# Inspect reshaped data
str(e3_reshape)

# Save reshaped file
write.csv(e3_reshape, "e3_reshape_data.csv", row.names = FALSE)

# Verify file creation
str(read.csv("e3_reshape_data.csv"))
```

